// <auto-generated />
using System;
using Akvelon.TokenService.DataLayer.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Akvelon.TokenService.DataLayer.Migrations
{
    [DbContext(typeof(TokenDbContext))]
    [Migration("20210412163116_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Akvelon.TokenService.Core.Models.Callback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HttpResponseCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("PK_CallBack");

                    b.ToTable("Callbacks");
                });

            modelBuilder.Entity("Akvelon.TokenService.Core.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Request");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Akvelon.TokenService.Core.Models.Callback", b =>
                {
                    b.HasOne("Akvelon.TokenService.Core.Models.Request", "Request")
                        .WithOne("Callback")
                        .HasForeignKey("Akvelon.TokenService.Core.Models.Callback", "Id")
                        .HasConstraintName("FK_Request_CallBack")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Akvelon.TokenService.Core.Models.Request", b =>
                {
                    b.Navigation("Callback");
                });
#pragma warning restore 612, 618
        }
    }
}
